services:
    app.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\User

    app.registration_controller:
       class: AppBundle\Controller\RegistrationController
       arguments:
           - @translator
           - @templating
           - @session
           - @form.factory

    app.admin_form:
        class: AppBundle\Form\UserType
        tags:
            - { name: form.type, alias: userform }
    app.admin_controller:
        class: AppBundle\Controller\AdminController
        arguments:
           - @translator
           - @templating
           - @session
           - @router
           - @security.context
           - @app.user_repository
           - @form.factory
           - @doctrine.orm.entity_manager

    app.tag_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Tag

    app.tag_form:
        class: AppBundle\Form\TagType
        tags:
            - { name: form.type, alias: tag }

    app.tags_controller:
        class: AppBundle\Controller\TagsController
        arguments:
            - @translator
            - @templating
            - @session
            - @router
            - @security.context
            - @app.tag_repository
            - @app.question_repository
            - @form.factory

    app.category_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Category
    app.category_form:
        class: AppBundle\Form\CategoryType
        tags:
            - { name: form.type, alias: category }
    app.categories_controller:
        class: AppBundle\Controller\CategoriesController
        arguments:
           - @translator
           - @templating
           - @session
           - @router
           - @security.context
           - @app.category_repository
           - @form.factory

    app.question_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Question
    app.question_form:
        class: AppBundle\Form\QuestionType
        tags:
            - { name: form.q_type, alias: question }
    app.question_answer_form:
        class: AppBundle\Form\AnswerType
        tags:
            - { name: form.a_type, alias: answer }
    app.questions_controller:
        class: AppBundle\Controller\QuestionsController
        arguments:
           - @translator
           - @templating
           - @session
           - @router
           - @security.context
           - @app.question_repository
           - @app.tag_repository
           - @app.category_repository
           - @app.answer_repository
           - @app.user_repository
           - @form.factory

    app.answer_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Answer
    app.answer_form:
        class: AppBundle\Form\AnswerType
        tags:
            - { name: form.type, alias: answer }
    app.answers_controller:
        class: AppBundle\Controller\AnswersController
        arguments:
           - @translator
           - @templating
           - @session
           - @router
           - @security.context
           - @app.question_repository
           - @app.answer_repository
           - @app.user_repository
           - @form.factory